fix: use fetch() instead of non-existent _fastly.request() in linkResource
The @adobe/fastly-native-promises library doesn't expose a request() method.
Using this.fetch() with full URL and headers instead.

Fixes integration test error: 'this._fastly.request is not a function'

Signed-off-by: Lars Trieloff <lars@trieloff.net>